version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      java: corretto8
    commands:
      - echo Entered the install phase...
      - echo About to build $RESOURCE_PATH
      - export PATH="/usr/local/bin:$PATH"
      - /usr/local/bin/dockerd-entrypoint.sh
      - cat /var/log/docker.log
      - echo java version
      - java -version
      - pwd
      - ls

  build:
    commands:
      - echo Entered the build phase...
      - mvn package -DskipTests
      - cd $RESOURCE_PATH
      - pwd
      - ls
      - ./setup.sh
      - ../publish-resource-regions.sh
    finally:
      - cat rpdk.log
      - ./cleanup.sh
