---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template describes an example resource type for giving a group permissions on a project
Resources:
  GitlabGroupAccessToProject:
    Type: GitLab::Projects::GroupAccessToProject
    Properties:
      ProjectId: 33430825
      GroupId: 16020673
      AccessLevel: Maintainer
