AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the GitLab::Projects::GroupAccessToProject resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 512

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.gitlab.aws.cfn.resources.projects.member.group.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/gitlab-projects-groupaccesstoproject-1.0.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.gitlab.aws.cfn.resources.projects.member.group.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/gitlab-projects-groupaccesstoproject-1.0.0-SNAPSHOT.jar

