---
AWSTemplateFormatVersion: '2010-09-09'
Description: Shows how to add a GitLab user to a GitLab project
Resources:
  MyUserJoiningAProject:
    Type: GitLab::Groups::UserMemberOfProject
    Properties:
      ProjectId: 16020673
      UserId: 1092680           # or Username
      AccessLevel: Maintainer
