---
AWSTemplateFormatVersion: '2010-09-09'
Description: Shows how to create a GitLab project
Resources:
  GitlabProject:
    Type: GitLab::Projects::Project
    Properties:
      Name: sample-project
