---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template describes an example resource type for creating a gitlab project
Parameters:
  Name:
    Default: test_project
    Description: Project name
    MinLength: '1'
    Type: String
Resources:
  GitlabNewProject:
    Type: CloudFormation::GitLab::Project
    Properties:
      Name: !Ref 'Name'
Outputs:
  Name:
    Description: Project name
    Value: !Ref 'Name'