AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Cloudformation::GitLab::Group resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.cloudformation.gitlab.group.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/cloudformation-gitlab-group-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.cloudformation.gitlab.group.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/cloudformation-gitlab-group-handler-1.0-SNAPSHOT.jar

